---
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: community.general
    version: ">=5.0.0"
  - name: amazon.aws
    version: ">=5.0.0"
  - name: azure.azcollection
    version: ">=1.14.0"
  - name: google.cloud
    version: ">=1.0.0"

roles:
  - name: geerlingguy.docker
    version: "4.1.0"