name: Ansible Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint
      
      - name: Run ansible-lint on Kubernetes playbooks
        run: |
          ansible-lint kubernetes/playbooks/*.yaml || true
      
      - name: Syntax check Kubernetes playbooks
        run: |
          for file in kubernetes/playbooks/*.yaml; do
            ansible-playbook "$file" --syntax-check
          done